force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/Module_Response__c.object-meta.xml
<CustomObject>
    <label>Module Response</label>
    <nameField>
        <label>Module Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Module Responses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module_Response__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Module Responses</relationshipLabel>
    <relationshipName>Module_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <label>Unit Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/fields/Number_of_Tries__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tries__c</fullName>
    <label>Number of Tries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UnitService.cls
public class UnitService{

    public static Boolean registerUnitResponse(Id unitId, String jsonAnswer){
        
        Database.SavePoint sp = Database.setSavePoint();

        try{
            Unit__c unit = [SELECT Module__c, (SELECT Id, Number_Of_Tries__c 
                           FROM Unit_Responses__r 
                           WHERE Module_Response__r.User__c =: UserInfo.getUserId() 
                           ORDER BY Number_Of_Tries__c DESC LIMIT 1), (SELECT Id, Name FROM Questions__r) FROM Unit__c WHERE Id =: unitId];
            
            Module_Response__c moduleResponse = [SELECT Id FROM Module_Response__c 
                                            WHERE Module__c =: unit.Module__c AND User__c =: Userinfo.getUserId() AND Status__c = 'In Progress'];
            
            if(moduleResponse == null){
                moduleResponse = new Module_Response__c(User__c = Userinfo.getUserId(), Module__c = unit.Module__c, Status__c = 'In Progress');
                insert moduleResponse;
            }

            Unit_Response__c unitResponse = new Unit_Response__c(Unit__c = unitId, Module_Response__c = moduleResponse.Id, Status__c = 'Draft');
            unitResponse.Number_Of_Tries__c = !unit.Unit_Responses__c.isEmpty() ? unit.Unit_Response__c[0].Number_Of_Tries__c + 1 : 1;
            insert unitResponse;
        }
    }
}